name: Create Flashable Release

on:
  push:
    tags:
      - 'v*'  # Trigger only when a version tag is pushed

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set module zip name
        run: |
          echo "ZIP_NAME=module-${GITHUB_REF#refs/tags/}.zip" >> $GITHUB_ENV

      - name: Create flashable ZIP
        run: |
          zip -r $ZIP_NAME . -x "*.git*" "*.github*" ".DS_Store" "*README.md"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
