name: Auto Version & Release

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  version-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for full commit history




      - name: Update module.prop
        run: |
          sed -i "s/^version=.*/version=${{ steps.version.outputs.version }}/" module.prop
          sed -i "s/^versionCode=.*/versionCode=${{ steps.version.outputs.versionCode }}/" module.prop

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "🔖 Release v${{ steps.version.outputs.version }}"
          git tag v${{ steps.version.outputs.version }}
          git push origin HEAD --tags

      - name: Generate changelog since last tag
        id: changelog
        run: |
          # Get latest tag (e.g. v1.0.2)
          LAST_TAG=$(git describe --tags --abbrev=0)
          echo "Last tag: $LAST_TAG"

          # Extract log since last tag, skip merge commits
          LOG=$(git log "$LAST_TAG"..HEAD --no-merges --pretty=format:"- %s (%an)")
          echo "log<<EOF" >> $GITHUB_ENV
          echo "$LOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV


      - name: Set zip name
        run: |
          echo "ZIP_NAME=TerminalSystemizer-${{ steps.version.outputs.version }}.zip" >> $GITHUB_ENV

      - name: Create flashable zip
        run: |
          zip -r $ZIP_NAME . -x "*.git*" "*.github*" ".DS_Store" "*README.md"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: ${{ env.log }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

